weights: ''
cfg: models/resnet50.yaml
data: CamVid/data.yaml
epochs: 100
batch_size: 16
imgsz: 640
device: ''
workers: 8
freeze:
- 0
patience: 10
single_cls: false
sync_bn: false
cos_lr: false
resume: false
save_dir: runs/train-seg
optimizer: SGD
label_smoothing: 0.0
seed: 0
noval: false
nosave: false
noplots: false
cache: null
rect: false
image_weights: false
quad: false
evolve: false
hyp: data/hyps/hyp.scratch-seg.yaml
