weights: ''
cfg: vgg16.yaml
data: /root/BestYOLO/CamVid/data.yaml
epochs: 300
batch_size: 8
imgsz: 640
device: ''
workers: 8
freeze:
- 0
patience: 30
single_cls: false
sync_bn: false
cos_lr: false
resume: false
save_dir: runs/train-diceloss-vgg16
optimizer: SGD
label_smoothing: 0.0
seed: 0
noval: false
nosave: false
noplots: false
cache: null
rect: false
image_weights: false
quad: false
evolve: false
hyp: /root/BestYOLO/data/hyps/hyp.scratch-seg.yaml
exist_ok: false
